CREATE DATABASE IF NOT EXISTS deepHabitatDB;

USE deepHabitatDB;

CREATE TABLE IF NOT EXISTS users(
	id	BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    name VARCHAR(255),
    password VARCHAR(255)
);